### ISSUE TITLE
Connection removal removes all connection instead of one

### ISSUE THREAD

**Issue by Rulino** [DimensionLab/simlai-issues#2]
https://github.com/DimensionLab/simlai-issues/assets/43948534/e818c05d-2b4f-4aff-94cb-540ee0c7b04c

When I try to remove a single connection, all of the connections are removed.

**Comment by michaltakac** [comment]
@6feferonka9 please take a look at this.

**Comment by michaltakac** [comment]
@Rulino should be fixed in the latest version of Siml.ai platform (available in staging and production).
